name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # งาน CI - ทดสอบและตรวจสอบคุณภาพโค้ด
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

    #   - name: Run tests
    #     run: npm test || true # ให้งานสำเร็จแม้ว่าการทดสอบจะล้มเหลว (อาจปรับตามความเหมาะสม)

  # งาน CD - สร้างและเผยแพร่ Docker image
  build-and-deploy:
    needs: test # รอให้งานทดสอบสำเร็จก่อน
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # ดำเนินการเฉพาะเมื่อ push ไปที่ main

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-app:latest,${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-app:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/nextjs-app:buildcache,mode=max
